# nfs chart attributs :
nfs-subdir-external-provisioner:
  storageClass:
    name: nfs-client
    reclaimPolicy: Delete
    allowVolumeExpansion: true
    defaultClass: true

  nfs:
    server: 192.168.40.4
    path: /data/nfs
# namespace : 
namespace: nexus
# deployment attributs : 
Deployment:
  name: nexus-server-java
  replicas: 1
  labels:
    name: nexus-server-java
  volumes: 
    name: nexus-vol
    persistentVolumeClaim:
      claimName: nexus-java-pvc
  container: 
    name: nexus-java
    image: sonatype/nexus3:3.64.0
    resources:
      limits:
        memory: "4Gi"
        cpu: "1000m"
      requests: 
        memory: "2Gi"
        cpu: "500m"
    volumeMounts: 
      name: nexus-vol
# service attributs :
service: 
  name: nexus-java
  ports:
    port: 8081
    nodePort: 32321
  type: NodePort

  # Persistent Volume Claim attributs :
pvc:
  name: nexus-java-pvc
  storageClassName: nfs-client
  resources: 
    requests:
      storage: 5Gi