apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.Deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.Deployment.labels.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.Deployment.labels.name }}
    spec:
      volumes:
        - name: {{ .Values.Deployment.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.Deployment.volumes.persistentVolumeClaim.claimName }}
      containers:
        - name: {{ .Values.Deployment.container.name }}
          image: {{ .Values.Deployment.container.image }}
          resources:
            limits:
              memory: {{ .Values.Deployment.container.resources.limits.memory }}
              cpu: {{ .Values.Deployment.container.resources.limits.cpu }}
            requests:
              memory: {{ .Values.Deployment.container.resources.requests.memory }}
              cpu: {{ .Values.Deployment.container.resources.requests.cpu }}
          ports:  
            - containerPort: 8081
          volumeMounts:
            - name: {{ .Values.Deployment.container.volumeMounts.name }}
              mountPath: /nexus-data
