apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-js-pvc
  namespace: devops-tools
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
