apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: devops-tools
spec:
  selector:
    app: {{ .Values.Deployment.labels.name }}
  ports:
  - port: {{ .Values.service.ports.port }}
    targetPort: 8081
    nodePort: {{ .Values.service.ports.nodePort }}
  type: {{ .Values.service.type }}
