apiVersion: v1
kind: Service
metadata:
  name: nexus-java
  namespace: devops-tools
spec:
  selector:
    app: nexus-server-java
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 32321
  type: NodePort
